server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    #最大工作线程数，默认200, 4核8g内存，线程数经验值800
    #操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000
    # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
    threads:
      min-spare: 100
      max: 1000
spring:
  r2dbc:
    url: r2dbc:mysql://123.57.136.219:13147/learn?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: aA5855889
